### ISSUE TITLE
Create a kubearmor-integrations /docs directory 

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/kubearmor-integration#2]
The Open Horizon documentation site can incorporate documentation from various Open Horizon repositories. We use a GitHub Action to copy over markdown / images / etc files from the subproject repo into the https://open-horizon.github.io/ site.

Once there is a /docs directory in this repo, we can implement the GHA.
https://github.com/open-horizon/open-horizon.github.io/issues/304

**Comment by johnwalicki** [comment]
@Ankurk99 noticed a leading / in the copy-docs.yaml GHA and fixed it in:
I pushed a change to the README.md  See: https://github.com/open-horizon/kubearmor-integration/commit/958bef742d4ab9ea1ccde66f0f4c37ebd5aadbee
I merged the PR #10 and the Copy-Docs GHA ran:
but failed with
```
fatal: could not read Password for 'https://***@github.com': No such device or address
```

**Comment by johnwalicki** [comment]
We're trying to use the open-horizon org secret PERSONAL_TOKEN from
https://github.com/organizations/open-horizon/settings/secrets/actions
but the copy-docs.yaml  `dst_owner: open-horizon`
doesn't work.

It says
```
Secrets are environment variables that are encrypted. Anyone with collaborator access to the repositories with access to each secret can use it for Actions. 
```

**Comment by Ankurk99** [comment]
Ah! Just noticed something:
The PR https://github.com/open-horizon/kubearmor-integration/commit/6fbc82cb3c17ca2088e9527fbe189d82d44b079c removed the previous changes added in the PR #4 (But I am still confused why it was not removed in the PR #5 itself). So currently we don't have the docs folder. Also I think we also will need to update the src_path (https://github.com/open-horizon/kubearmor-integration/blob/main/.github/workflows/copy-docs.yml#L19) in the GA.
But I am still not sure if the error to not be able to read password be fixed with these changes.

**Comment by johnwalicki** [comment]
Quite possibly we can edit L19 to remove the leading `/`
In the GHA run I see the double slash.
 `Copying "kubearmor-integration//README.md" and pushing it to open-horizon/open-horizon.github.io`

**Comment by johnwalicki** [comment]
Before we ran the GHA, I created a docs/kubearmor-integration/tmpfile in the open-horizon.github.io repo. See https://github.com/open-horizon/open-horizon.github.io/commit/70f1402b2555ae211335afa12ca5d51b26fb1d85

Maybe I should have also created a `docs/kubearmor-integration/docs` directory too.

**Comment by Ankurk99** [comment]
I have restored the docs folder and have tried to updated the GA to replicate the format of other open-horizon github actions, please take a look if the fix is fine.

**Comment by johnwalicki** [comment]
It looks correct.  GHA fails on the secret / password.
```
  3 files changed, 259 insertions(+)
 create mode 100644 docs/kubearmor-integration/docs/OH-detailed.png
 create mode 100644 docs/kubearmor-integration/docs/OH-edge-kubearmor.png
 create mode 100644 docs/kubearmor-integration/docs/README.md
fatal: could not read Password for 'https://***@github.com': No such device or address
```

**Comment by johnwalicki** [comment]
I'm looking at the source code for the CopyCat GHA
https://github.com/andstor/copycat-action/blob/master/entrypoint.sh

**Comment by johnwalicki** [comment]
I cloned and built the copycat container on my local system.   Figured out what params to pass it by studying the output of one of the GHA copycat runs.
Still failed with the same error.  With some additional experiments:
```
[master 0dcaf29] Update file(s) "docs" from "open-horizon/kubearmor-integration"
 3 files changed, 259 insertions(+)
 create mode 100644 docs/kubearmor-integration/docs/OH-detailed.png
 create mode 100644 docs/kubearmor-integration/docs/OH-edge-kubearmor.png
 create mode 100644 docs/kubearmor-integration/docs/README.md
git push with this syntax
git push origin master
fatal: remote origin already exists.
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/open-horizon/open-horizon.github.io.git/'
Copying complete 
```

I modified the entrypoint.sh for copycat to use my PAT based the answer in this StackOverflow discussion.
https://stackoverflow.com/questions/31159275/how-do-i-generate-the-github-oauth-token-for-organization-accounts

I replace the `git push origin` with 
```
    git remote show origin
    git remote set-url origin https://<john-PAT-with-org-admin-privs>@github.com/open-horizon/open-horizon.github.io.git
    git push -u origin ${DST_BRANCH}
```
Running it local finally succeeded (using a PAT that I created over in github/johnwalicki)   This isn't the right answer but it shows the problem with trying to use this GHA in an Org, not a personal github account.

**Comment by johnwalicki** [comment]
I learned a lot about how the CopyCat GitHub Action executes. I offered to improve their documentation so others can run it in a GitHub Org.  See https://github.com/andstor/copycat-action/issues/65

Closing this ticket as complete.  Thanks to the AccuKnox team for contributing to Open Horizon.
