### ISSUE TITLE
Add missing externalLink directive to README

### ISSUE THREAD

**Issue by dipesh-rawat** [open-horizon/kubearmor-integration#20]
The [README.md](https://github.com/dipesh-rawat/kubearmor-integration/blob/main/README.md?plain=1#L21) in this repo is not correctly using the {:target="_blank"}{: .externalLink} directive.

**Comment by johnwalicki** [comment]
The KubeArmor README also needs front matter directives so that it appears in the navigation sidebar (under the `Integrating` parent)
